### ISSUE TITLE
licence [take 3] 

### ISSUE THREAD

**Issue by picca** [PierreRaybaut/python-qwt#15]
Hello Pierre,

I need to do the license review for Debian and I can not find the license information of the
toqimage.py file. It seems to be a common snipset used on internet but I have no idea of the license.

also on thaht I have the examples, I need also the license.

Once done, I think that it will be ok from my point of view and ready to upload into Debian experimental.

thanks

**Comment by uwerat** [comment]
The majority of all examples is again simply ported from the Qwt examples, but in opposite to the library itself I never added any license explicitly. Never cared for this before, but from the formal point of view it probably means, that this code is also under the Qwt license ( like any other file of the package, where you don't find  exceptions ).

But I can also see code that might be copied/derived from Gerads package, what had been released under the GPL. But Pierre will know better on those ...

**Comment by PierreRaybaut** [comment]
Ok, I'm taking care of the examples (PyQwt license will apply).
@picca As for the toqimage.py license, I don't know what to do... so MIT license will apply (there is no reason that Qwt license should apply on this part of the code).

Oh, BTW, @uwerat, did you know that there is absolutely no copyright with your name in README, COPYING, ... in the PyQwt source package? Is it a special treatment for python-qwt?

**Comment by PierreRaybaut** [comment]
Ok, so, as you can see in commit above, that is done.

Ok for you?

**Comment by picca** [comment]
from my point of view this is ok. the copyright is missing in toqimage, but the amount of code is so small that I think that the ftp-master team will be ok. Just put yourself as copyright owner.

**Comment by uwerat** [comment]
The PyQwt project is different to this one as it does a language binding only. In the end it is like any other project using Qwt as a C++ library.

When talking about the PyQwt examples you are right: I could claim copyright for this code as well. So yes, you have to add my copyright to some of the examples as well ( some of them are 100% Gerards code ).

But please don't ask me for fiddling out which code belongs where - I'm not interested enough in the code of the examples.

ciao,
Uwe

**Comment by PierreRaybaut** [comment]
Well then let's not complicate things more than they are. I've added only the PyQwt license/copyright to the examples.

But my comment above "@uwerat, did you know that there is absolutely no copyright with your name in README, COPYING, ... in the PyQwt source package? Is it a special treatment for python-qwt?" was *not* referring to examples but to the PyQwt package itself. Apparently what seems so mandatory to you today for python-qwt was not yesterday with PyQwt!! That is giving me a new perspective on your intentions.

**Comment by uwerat** [comment]
The PyQwt tarball contains a subfolder with an unmodified Qwt 5.2 package, including all copyrights and licenses. Gerard did everything very correct and all code he has released under his copyright is his and only his work. So all you wrote about the PyQwt package is simply wrong - please stop it. 

I also don't understand what "intentions" you have in mind. What happened is, that you were claiming property for a development of almost 20 years, where you never contributed any single line of code. In this context it comes quite bizarre, when reading allegations against others from your side.

**Comment by PierreRaybaut** [comment]
I was referring to the fact that you want your copyright everywhere and that it's not the case with PyQwt. But nevermind. You really think that I would have benefit from this so-called code theft? That's simply ridiculous. Of course the license you first read was an unfinished work and that's all it was. Period. Now if you can't understand that...
And you're not entirely right by the way, I wrote every single line of the Python translation. Hence the copyright*s* that can now be read at every file header.

**Comment by picca** [comment]
Just for info nowadays there is no pyqwt binding on top of qwt6.
Every peoples I know about whom tryed to create a binding on top of qwt6 gave-up.
no offence this is just a fact.

So peoples which choosed pyqwt technologie had no solution other than migrating to another solution, like pyqtgraph or other home made solution in order to support qt5.

the work done by Pierre is really valuable because it still acknowledge that all this comes from qwt.

Yes he did the mistake to publish this unfinish work, I did the mistake to upload this into Debian becasue I was really enthousiast to provide a solution to our users.

Now it seems to me that the problem is solved.

Cheers and good night.

Keep up the good work both of you :)

Frederic

**Comment by PierreRaybaut** [comment]
@picca Your last comment justifies reopening this issue before closing it definitely. This is a good conclusion.

I personally apologize for being so tense these last days but I spent hours trying to fix that mistake and it never seemed to be enough.

So @uwerat I think now would be the time to move on and to recognize that the source package license and copyright informations are now more than fair regarding the original Qwt C++ project.
So, do you agree and can we close definitely this issue?

**Comment by uwerat** [comment]
The current state of the repository looks promising, but I need more time to give my final o.k. Please understand that this might take some time - I also have other things to do.

But my primary concern is and was to fix and recall the bad versions, so that the wrong information given there doesn't make its way even further. So one imoportant task is still not done: releasing and announcing a correct new version of the package !

@picca: AFAIK you might be wrong ( not taken as offense ) - but as I'm not involved it's not me to write more about it.

**Comment by picca** [comment]
Just for info, I filled a request in order to remove the NEW python-qwt package fromDebian

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=797150

**Comment by uwerat** [comment]
Did a very brief check of the guiqwt package and indeed there is code that looks similar to code from the PyQwt examples. To check the history of this code I downloaded guiqwt-2.0.3 and did a:
"diff guiqwt-2.0.3/guiqwt PyQwt-5.2.0/qt4examples/ErrorBarDemo.py"

Judge yourself, but if this code is really based on Gerards code and you didn't have permission from him, he has a copyright and the PyQwt license rules for probably any version of guiqwt, that has been released so far.

As this is not my business I didn't check any other code and leave it up to you to take care, that this project is on a legal path ...

ciao,
Uwe

**Comment by PierreRaybaut** [comment]
Nothing in guiqwt is based on PyQwt code. There is a confusion between *using* a library and *deriving from* a library. The guiqwt library is *using* PyQt, PyQwt, NumPy and SciPy but there is no code of these libraries that was inspired from or included in any way.

I'm sure that if you compare the implementation of every single classic data processing algorithm, you will find similarities (in this example, there aren't many possibilities when implementing an error bar curve using Qwt/Qt). Does it mean that the first guy who implemented this algorithm has a copyright on it? No, of course not. This way of reasoning is not only very simplistic but also the exact opposite of the open-source software development spirit. That's a very "software patent" thinking (yuck...).

So, please leave guiqwt out of this discussion. "Stop it", as you wrote at another occasion of our wonderful discussions.

Regarding the release and announcement of a new version of python-qwt, I don't understand your request because I didn't do anything more for the v6.1.2a3 (the intermediate/unfinished/... package you discovered and that got you legitimately angry) than I did for the v6.1.2a5. Oh, I did tweet about python-qwt. I'm tweeting right now about v6.1.2a5. So, there is nothing more to do in this area neither (phew...).

So, we are waiting for your final ok, of course. But, given the amount of work which was done this week, I consider this is no more a blocking nor a first priority issue.

**Comment by picca** [comment]
Hello

what is strange is that a python-qwt 6.1.2a6 is available on pypi but it doesn not contain the latest license modifications. and there is no a6 tag in the git repository.

see you

**Comment by PierreRaybaut** [comment]
Damn I'm checking this right now. Thanks.

**Comment by PierreRaybaut** [comment]
@picca Indeed, the v6.1.2a5 was not including the very last license but an intermediate version but this was already very acceptable for @uwerat as there was absolutely no copyright with my name on it on this one. So no harm done this time.

**Comment by PierreRaybaut** [comment]
Oh, by the way, I've released v6.1.2a7 to replace it.

**Comment by picca** [comment]
ok, so just waiting for uwerat for the debian upload of a7.

thanks

**Comment by uwerat** [comment]
@Pierre

Concerning guiqwt vs. PyQwt:

when comparing ErrorBarCurveItem::draw ( errorbar.py from guiqwt-2.0.3 ) with ErrorBarPlotCurve::drawFromTo ( PyQwt-5.2.0 ) I can see comments that were copied 1:1.

These comments are about a class "QwtDiMap" - a class from Qwt4 ( Gerard forgot to update his comments, when migrating to Qwt5 ), that had disappeared long before guiqwt was released.  I can also see comments explaining the meaning of parameters, that only exist in Gerards version.

But as my interests are not concerned this conversation ends for me at this point.

@picca:

I would like to see a replacement for the bad versions a.s.a.p. - so please go ahead.

If there are issues left I will report them here, when I found time to have a look at. But to be honest I'm really tired of having to spend time on this all and this also might never happen. So I would like to ask you to take care, that things are done more correct in the future.

Many thanks in advance !

ciao,
Uwe

**Comment by PierreRaybaut** [comment]
guiqwt: you may have found the only small piece of code that may be problematic (I don't remember the details as this is quite old) but this is so insignificant... AFAIK, everything was written from scratch in guiqwt. That's why we thought of replacing PyQwt by python-qwt: at the end, we are not using much of the Qwt API (the event manager is our own, the image display engine is so much more powerful, and so on)... it leaves only the axes and the canvas.

python-qwt: Ok, so I'll let you open a new issue if you have another request in this area.
